version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: 'npm run dev'
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=proxima
      - TYPEORM_PASSWORD=proxima
      - TYPEORM_DATABASE=proxima
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_PORT=5432
      - TYPEORM_ENTITIES=src/entity/**/*.ts
      - TYPEORM_MIGRATIONS=src/migration/**/*.ts
      - TYPEFORM_ID
      - TYPEFORM_TOKEN
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
  postgres:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=proxima
      - POSTGRES_PASSWORD=proxima
      - POSTGRES_DB=proxima
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U proxima -d proxima']
      interval: 10s
      timeout: 5s
      retries: 5
